module: Amplify
module_version: 0.11.0
author: Amazon Web Services
github_url: https://github.com/aws-amplify/amplify-ios

exclude:
- Pods

clean: true
skip_undocumented: false
sdk: iphone
theme: apple
