# .circleci/config.yml

version: 2.1

defaults: &defaults
  macos:
    xcode: "11.2.1"
  working_directory: /Users/distiller/project

references:
  repo_cache_key: &repo_cache_key 1-repo-{{ .Branch }}-{{ .Revision }}
  
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key
        - 1-repo-{{ .Branch }}
        - 1-repo-

commands:
  restore_gems:
    steps:
      - restore_cache:
          keys:
            - 1-gems-{{ checksum "/Users/distiller/project/Gemfile.lock" }}
            - 1-gems-
  save_plugin_pods:
    parameters:
      prefix:
        type: string
    steps:
      - save_cache:
          key: 1-<< parameters.prefix >>-dependency-pods-{{ checksum "Podfile" }}
          paths:
            - ./Pods
  restore_plugin_pods:
    parameters:
      prefix:
        type: string
    steps:
      - restore_cache:
          keys:
            - 1-<< parameters.prefix >>-dependency-pods-{{ checksum "Podfile" }}
            - 1-<< parameters.prefix >>-dependency-pods-

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths:
            - /Users/distiller/project

  install_gems:
    <<: *defaults
    environment:
      BUNDLE_PATH: vendor/bundle
    steps:
      - *restore_repo
      - restore_gems
      - run:
          name: Bundle install
          # bundle ignores BUNDLE_PATH unless it's explicitly passed in
          command: bundle check --path $BUNDLE_PATH || bundle install --path $BUNDLE_PATH
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          key: 1-gems-{{ checksum "/Users/distiller/project/Gemfile.lock" }}
          paths:
            - vendor/bundle         
  
  build_test_amplify:
    <<: *defaults
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      BUNDLE_PATH: vendor/bundle
    shell: /bin/bash --login -o pipefail
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths:
            - /Users/distiller/project
      - restore_gems
      - run: pod install
      - run:
          name: Bundle check
          command: bundle check --path $BUNDLE_PATH || bundle install --path $BUNDLE_PATH
      - run:
          name: fastlane test
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build_test:
    jobs:
      - checkout_code
      - install_gems:
          requires:
            - checkout_code
      - build_test_amplify:
          requires:
            - install_gems