# .circleci/config.yml

version: 2.1


defaults: &defaults
  macos:
    xcode: "11.2.1"
  working_directory: ~/amplify-ios


references:
  repo_cache_key: &repo_cache_key
    v1-repo-{{ .Branch }}-{{ .Revision }}

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key
        - v1-repo-{{ .Branch }}
        - v1-repo

  pods_cache_key: &pods_cache_key
    v1-dependency-pods-{{ checksum "~/amplify-ios/Podfile" }}
  
  pods_backup_cache_key: &pods_backup_cache_key
    v1-dependency-pods

  restore_pods: &restore_pods
    restore_cache:
      keys:
        - *pods_cache_key
        - *pods_backup_cache_key


commands:
  pre_start_simulator:
    description: >-
      pre start simulator, build may fail is simulator is not started
    steps:
      - run:
          name: pre-start simulator
          command: bash CircleciScripts/pre_start_simulator.sh

  api_unit_tests:
    steps:
      - run: ls -alF


jobs:
  checkout_code:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths: 
            - ~/amplify-ios

  install_pods:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_pods
      - run: pod install
      - save_cache:
          key: *pods_cache_key
          paths:
            - ~/amplify-ios/Pods
            - ~/amplify-ios/Amplify.xcworkspace

  build_amplify:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_pods      
      - pre_start_simulator   
      - run:
          name: build amplify
          command: xcodebuild build -workspace Amplify.xcworkspace -scheme Amplify -sdk iphonesimulator -destination "${destination}"
  
  unit_test:
    <<: *defaults
    working_directory: ~/amplify-ios/AmplifyPlugins
    steps:
      - *restore_repo
      - *restore_pods
      - api_unit_tests


workflows:
  build_test:
    jobs:
      - checkout_code
      - install_pods:
          requires:
              - checkout_code        
      - build_amplify:
          requires:
              - install_pods                
      - unit_test:
          requires:
              - build_amplify
